export const ADMIN_SAVE_PROMOTED_PRODUCT_PACKAGE = "ADMIN_SAVE_PROMOTED_PRODUCT_PACKAGE";
export const ADMIN_SAVE_PROMOTED_PRODUCT_PACKAGE_SUCCESS = "ADMIN_SAVE_PROMOTED_PRODUCT_PACKAGE_SUCCESS";
export const ADMIN_SAVE_PROMOTED_PRODUCT_PACKAGE_FAIL = "ADMIN_SAVE_PROMOTED_PRODUCT_PACKAGE_FAIL";

export const ADMIN_LIST_PROMOTED_PRODUCT_PACKAGE = "ADMIN_LIST_PROMOTED_PRODUCT_PACKAGE";
export const ADMIN_LIST_PROMOTED_PRODUCT_PACKAGE_SUCCESS = "ADMIN_LIST_PROMOTED_PRODUCT_PACKAGE_SUCCESS";
export const ADMIN_LIST_PROMOTED_PRODUCT_PACKAGE_FAIL = "ADMIN_LIST_PROMOTED_PRODUCT_PACKAGE_FAIL";

export const ADMIN_DELETE_PROMOTED_PRODUCT_PACKAGE = "ADMIN_DELETE_PROMOTED_PRODUCT_PACKAGE";
export const ADMIN_DELETE_PROMOTED_PRODUCT_PACKAGE_SUCCESS = "ADMIN_DELETE_PROMOTED_PRODUCT_PACKAGE_SUCCESS";
export const ADMIN_DELETE_PROMOTED_PRODUCT_PACKAGE_FAIL = "ADMIN_DELETE_PROMOTED_PRODUCT_PACKAGE_FAIL";

export const ADMIN_GET_PROMOTED_PRODUCT_PACKAGE = "ADMIN_GET_PROMOTED_PRODUCT_PACKAGE";
export const ADMIN_GET_PROMOTED_PRODUCT_PACKAGE_SUCCESS = "ADMIN_GET_PROMOTED_PRODUCT_PACKAGE_SUCCESS";
export const ADMIN_GET_PROMOTED_PRODUCT_PACKAGE_FAIL = "ADMIN_GET_PROMOTED_PRODUCT_PACKAGE_FAIL";

export const ADMIN_UPDATE_PROMOTED_PRODUCT_PACKAGE = "ADMIN_UPDATE_PROMOTED_PRODUCT_PACKAGE";
export const ADMIN_UPDATE_PROMOTED_PRODUCT_PACKAGE_SUCCESS = "ADMIN_UPDATE_PROMOTED_PRODUCT_PACKAGE_SUCCESS";
export const ADMIN_UPDATE_PROMOTED_PRODUCT_PACKAGE_FAIL = "ADMIN_UPDATE_PROMOTED_PRODUCT_PACKAGE_FAIL";

export const ADMIN_LIST_PROMOTED_PRODUCT_EXPIRED = "ADMIN_LIST_PROMOTED_PRODUCT_EXPIRED";
export const ADMIN_LIST_PROMOTED_PRODUCT_EXPIRED_SUCCESS = "ADMIN_LIST_PROMOTED_PRODUCT_EXPIRED_SUCCESS";
export const ADMIN_LIST_PROMOTED_PRODUCT_EXPIRED_FAIL = "ADMIN_LIST_PROMOTED_PRODUCT_EXPIRED_FAIL";

export const ADMIN_UPDATE_PROMOTED_PRODUCT_EXPIRED = "ADMIN_UPDATE_PROMOTED_PRODUCT_EXPIRED";
export const ADMIN_UPDATE_PROMOTED_PRODUCT_EXPIRED_SUCCESS = "ADMIN_UPDATE_PROMOTED_PRODUCT_EXPIRED_SUCCESS";
export const ADMIN_UPDATE_PROMOTED_PRODUCT_EXPIRED_FAIL = "ADMIN_UPDATE_PROMOTED_PRODUCT_EXPIRED_FAIL";

/* ADMIN SAVE PROMOTED PACKAGE */
export function actionAdminSavePromotedPackage(promoted){
    return {
        type: ADMIN_SAVE_PROMOTED_PRODUCT_PACKAGE,
        promoted: promoted
    }
}

/* ADMIN LIST PROMOTED PACKAGE */
export function actionAdminListPromotedPackage(packaged){
    return {
        type: ADMIN_LIST_PROMOTED_PRODUCT_PACKAGE,
        packaged: packaged
    }
}


/* ADMIN GET PROMOTED PACKAGE */
export function actionAdminGetPromotedPackage(id){
    return {
        type: ADMIN_GET_PROMOTED_PRODUCT_PACKAGE,
        id: id
    }
}

/* ADMIN UPDATE PROMOTED PACKAGE */
export function actionAdminUpdatePromotedPackage(promoted){
    return {
        type: ADMIN_UPDATE_PROMOTED_PRODUCT_PACKAGE,
        promoted: promoted
    }
}

/* ADMIN DELETE PROMOTED PACKAGE */
export function actionAdminDeletePromotedPackage(id){
    return {
        type: ADMIN_DELETE_PROMOTED_PRODUCT_PACKAGE,
        id: id
    }
}

/* ADMIN LIST PROMOTED PRODUCTS EXPIRED */
export function actionAdminListPromotedProductsExpired(products){
    return {
        type: ADMIN_LIST_PROMOTED_PRODUCT_EXPIRED,
        products: products
    }
}

/* ADMIN UPDATE PROMOTED PRODUCTS EXPIRED */
export function actionUpdatePromotedProductExpired(products){
    return {
        type: ADMIN_UPDATE_PROMOTED_PRODUCT_EXPIRED
    }
}